#!/usr/bin/env bash

NAMESPACE=$1
DOCKER_HOST_URL=$2
DOCKER_USERNAME=$3
DOCKER_PASSWORD=$4
DOCKER_EMAIL=$5
DOCKER_PULL_SECRET=$6
EXISTS=

kubectl create secret docker-registry ${DOCKER_PULL_SECRET} \
  --docker-server="${DOCKER_HOST_URL}" \
  --docker-username="${DOCKER_USERNAME}" \
  --docker-password="${DOCKER_PASSWORD}" \
  --docker-email="${DOCKER_EMAIL}" \
  --namespace ${NAMESPACE} || export EXISTS=yes

if [ ! -z ${EXISTS} ]; then
  kubectl delete secret ${DOCKER_PULL_SECRET} -n ${NAMESPACE}
  kubectl create secret docker-registry ${DOCKER_PULL_SECRET} \
  --docker-server="${DOCKER_HOST_URL}" \
  --docker-username="${DOCKER_USERNAME}" \
  --docker-password="${DOCKER_PASSWORD}" \
  --docker-email="${DOCKER_EMAIL}" \
  --namespace ${NAMESPACE}
fi
