#!/usr/bin/env bash
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
sudo chmod a+xX kubectl
sudo cp kubectl /usr/local/bin/kubectl
kubectl version || echo "Kubectl Failed to Install" && exit 1
sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash || echo "Helm Failed to Install" && exit 1

