#!/usr/bin/env bash
export PATH=libraries/utilities:${PATH}
export PATH=libraries/helm:${PATH}
export PATH=libraries/aws:${PATH}
export PATH=libraries/kubernetes:${PATH}
export PATH=libraries/terraform:${PATH}
export PATH=libraries/docker:${PATH}
echo "${PATH}" >> ${GITHUB_PATH}